/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author LENOVO
 */
public class Registerbolo extends javax.swing.JFrame {

    /**
     * Creates new form Loginbolo
     */
     
    public Registerbolo() {
        initComponents();
          Connect();
        this.setLocationRelativeTo(null);

    }
        Connection con;
       PreparedStatement pst;
      
    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/projectakhir", "root", "");
            } catch (SQLException ex) {
                Logger.getLogger(Registerbolo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registerbolo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtnamadepan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnamabelakang = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txttgllhr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1274, 555));

        jPanel3.setBackground(new java.awt.Color(48, 71, 94));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 232), 15));
        jPanel3.setPreferredSize(new java.awt.Dimension(1274, 555));

        jPanel1.setPreferredSize(new java.awt.Dimension(5, 579));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        txtnamadepan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnamadepan.setForeground(new java.awt.Color(153, 153, 153));
        txtnamadepan.setText("Enter First Name");
        txtnamadepan.setMargin(new java.awt.Insets(0, 5, 2, 2));
        txtnamadepan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamadepanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamadepanFocusLost(evt);
            }
        });
        txtnamadepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamadepanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 232, 232));
        jLabel1.setText("Sign Up");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 232, 232));
        jLabel11.setText("Masuk Ke Akun");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 84, 84));
        jLabel5.setText("PAWNSHOP");

        txtnamabelakang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnamabelakang.setForeground(new java.awt.Color(153, 153, 153));
        txtnamabelakang.setText("Enter Last Name");
        txtnamabelakang.setToolTipText("");
        txtnamabelakang.setMargin(new java.awt.Insets(0, 5, 2, 2));
        txtnamabelakang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamabelakangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamabelakangFocusLost(evt);
            }
        });
        txtnamabelakang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamabelakangMouseClicked(evt);
            }
        });
        txtnamabelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabelakangActionPerformed(evt);
            }
        });

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(153, 153, 153));
        txtusername.setText("Enter Username");
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        txtnotelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnotelp.setForeground(new java.awt.Color(153, 153, 153));
        txtnotelp.setText("Enter Nomor Telephone");
        txtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelpActionPerformed(evt);
            }
        });

        txtpassword.setForeground(new java.awt.Color(153, 153, 153));
        txtpassword.setText("password");
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        txttgllhr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttgllhr.setForeground(new java.awt.Color(153, 153, 153));
        txttgllhr.setText("YYYY-MM-DD");
        txttgllhr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttgllhrMouseClicked(evt);
            }
        });
        txttgllhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttgllhrActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 232, 232));
        jLabel2.setText("Daftar >");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 232, 232));
        jLabel3.setText("Reset");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtusername)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txtnamadepan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnamabelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtnotelp)
                        .addComponent(txtpassword)
                        .addComponent(txttgllhr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143)))
                .addGap(191, 191, 191))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnamabelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamadepan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttgllhr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.getAccessibleContext().setAccessibleDescription("");
        jPanel3.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamadepanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamadepanFocusGained
   if(txtnamadepan.getText().equals("USERNAME")){
   txtnamadepan.setText("");
   txtnamadepan.setForeground(Color.YELLOW);
    }
    }//GEN-LAST:event_txtnamadepanFocusGained

    private void txtnamadepanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamadepanFocusLost
         if(txtnamadepan.getText().trim().equals("")){
   txtnamadepan.setText("");
   txtnamadepan.setForeground(new Color(232,232,232));
    }
          
    }//GEN-LAST:event_txtnamadepanFocusLost

    private void txtnamabelakangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamabelakangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabelakangFocusGained

    private void txtnamabelakangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamabelakangFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabelakangFocusLost

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Loginbolo lgf = new Loginbolo();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
         try {
            String namadepan = txtnamadepan.getText();
            String namabelakang = txtnamabelakang.getText();
            String username = txtusername.getText();
            String telp = txtnotelp.getText();
            String tanggallahir = txttgllhr.getText();
            String password = String.valueOf(txtpassword.getPassword());
            
            
            pst=con.prepareStatement("insert into user (namadepan, namabelakang, username, nomortelp, tanggallahir, password) values (?,?,?,?,?,?)");
            pst.setString(1, namadepan);
            pst.setString(2, namabelakang);
            pst.setString(3, username);
            pst.setString(4, telp);
            pst.setString(5, tanggallahir);
            pst.setString(6, password);
            
           
            
            int k=pst.executeUpdate();
            
            if (k==1) {
                JOptionPane.showMessageDialog(this, "User Berhasil Didaftarkan");
             
                
            }else{
                JOptionPane.showMessageDialog(this, "User gagal Didaftarkan");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registerbolo.class.getName()).log(Level.SEVERE, null, ex);
        }
    

    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelpActionPerformed

    private void txttgllhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttgllhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttgllhrActionPerformed

    private void txttgllhrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttgllhrMouseClicked
        txttgllhr.setText("");
    }//GEN-LAST:event_txttgllhrMouseClicked

    private void txtnamabelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabelakangActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       txtnamadepan.setText("");
       txtnamabelakang.setText("");
       txtusername.setText("");
       txtnotelp.setText("");
       txttgllhr.setText("");
       txtpassword.setText("");
       
    }//GEN-LAST:event_jLabel3MouseClicked
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         try {
            String namadepan = txtnamadepan.getText();
            String namabelakang = txtnamabelakang.getText();
            String username = txtusername.getText();
            String telp = txtnotelp.getText();
            String tanggallahir = txttgllhr.getText();
            String password = String.valueOf(txtpassword.getPassword());
            
            
            pst=con.prepareStatement("insert into user (`namadepan`, `namabelakang`, `username`, `nomortelp`, `tanggallahir`, `password`) values (?,?,?,?,?,?)");
            pst.setString(1, namadepan);
            pst.setString(2, namabelakang);
            pst.setString(3, username);
            pst.setString(4, telp);
            pst.setString(5, tanggallahir);
            pst.setString(6, password);
            
           
            
            int k=pst.executeUpdate();
            
            if (k==1) {
                JOptionPane.showMessageDialog(this, "User Berhasil Didaftarkan");
             
                
            }else{
                JOptionPane.showMessageDialog(this, "User gagal Didaftarkan");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registerbolo.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtnamadepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamadepanActionPerformed
        txtnamadepan.setText(null);
    }//GEN-LAST:event_txtnamadepanActionPerformed

    private void txtnamabelakangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamabelakangMouseClicked
       txtnamabelakang.setText(null);
    }//GEN-LAST:event_txtnamabelakangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registerbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registerbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registerbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registerbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registerbolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtnamabelakang;
    private javax.swing.JTextField txtnamadepan;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txttgllhr;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
